FROM node:18-alpine
WORKDIR /app

# Copy only package files first for caching
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts

# Copy the rest of the app
COPY . .

# Expose React dev server port
EXPOSE 3000

# Start React development server
CMD ["npm", "start"]
